// export const brand = document.getElementById("value-input-brand")

export const brand = document.querySelector("#value-input-brand")
export const plate = document.querySelector("#value-input-plate")
export const year = document.querySelector("#value-input-year")
export const transmission = document.querySelector("#value-input-transmission")
export const km = document.querySelector("#value-input-km")
export const fuel = document.querySelector("#value-input-fuel")
export const details = document.querySelector("#value-input-details")
export const details2 = document.querySelector("#value-input-details-2")
export const price = document.querySelector("#value-input-price")
export const conditions = document.querySelector("#value-input-conditions")
export const optional = document.querySelector("#value-input-optional")
export const comments = document.querySelector("#value-input-comments")
